image: alpine

before_script:
- apk update
- apk add curl
- apk add doxygen
## Uncomment the following line if you use graphviz dot graphs
#- apk add ttf-freefont graphviz

test:
  script:
  - doxygen doxygen/Doxyfile
  except:
  - master
  
pages:
  script:
  - doxygen doxygen/Doxyfile
  - mv doxygen/output/html/ public/
#  - curl -w '\n' 'https://discordapp.com/api/webhooks/490435280973725697/zqhEWJfpxirgOe0A9E4DsU-xRfpc29hxDHsoAia5yFWEr2HwRFP03kKQMUOKdxgOtE1u' -d '{"content":"デプロイが完了しました。}' -XPOST
  - curl -H 'Accept\: application/json' -H 'Content-type\: application/json' -X POST -d '{"content"\:"デプロイが完了しました。"}' 'https\://discordapp.com/api/webhooks/490435280973725697/zqhEWJfpxirgOe0A9E4DsU-xRfpc29hxDHsoAia5yFWEr2HwRFP03kKQMUOKdxgOtE1u'
  artifacts:
    paths:
    - public
  only:
  - master
